In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data/water_potability.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

In [4]:
df = df.drop('Potability', axis = 1)

In [5]:
df.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000

In [6]:
df = df.fillna(df.mean())

In [8]:
df_input = df[['ph', 'Hardness', 'Solids', 'Conductivity', 'Turbidity']]

In [9]:
from sklearn.preprocessing import StandardScaler
columns = list(df_input.columns)
scaler = StandardScaler()
df_input[columns] = scaler.fit_transform(df_input)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_9960\1043223104.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_input[columns] = scaler.fit_transform(df_input)

In [10]:
df_input

                ph  Hardness    Solids  Conductivity  Turbidity
0    -6.043133e-16  0.259195 -0.139471      1.708954  -1.286298
1    -2.289339e+00 -2.036414 -0.385987      2.062575   0.684218
2     6.928678e-01  0.847665 -0.240047     -0.094032  -1.167365
3     8.409504e-01  0.547651  0.000493     -0.778830   0.848412
4     1.368569e+00 -0.464429 -0.460249     -0.343939   0.138786
...            ...       ...       ...           ...        ...
3271 -1.641587e+00 -0.081758  2.916188      1.240155   0.601124
3272  4.953704e-01 -0.085667 -0.534295     -0.417706  -1.497627
3273  1.591254e+00 -0.626829  1.270810      0.072263  -0.856007
3274 -1.329516e+00  1.041355 -1.144058     -0.288597   0.950797
3275  5.401509e-01 -0.038546 -0.525812     -1.221919  -2.124459

[3276 rows x 5 columns]

In [11]:
import pickle 
pickle.dump(scaler,open('scaler.pkl', 'wb'))

In [ ]:
df

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,-6.043133e-16,0.259195,-0.139471,0.112415,9.613574e-01,1.708954,-1.180651,1.306149,-1.286298
1,-2.289339e+00,-2.036414,-0.385987,-0.307694,3.145987e-15,2.062575,0.270597,-0.638480,0.684218
2,6.928678e-01,0.847665,-0.240047,1.360594,3.145987e-15,-0.094032,0.781117,0.001509,-1.167365
3,8.409504e-01,0.547651,0.000493,0.592008,6.395190e-01,-0.778830,1.255134,2.152874,0.848412
4,1.368569e+00,-0.464429,-0.460249,-0.363698,-6.541765e-01,-0.343939,-0.824357,-2.181599,0.138786
...,...,...,...,...,...,...,...,...,...
3271,-1.641587e+00,-0.081758,2.916188,0.028027,7.242640e-01,1.240155,-0.118075,0.018481,0.601124
3272,4.953704e-01,-0.085667,-0.534295,0.593290,3.145987e-15,-0.417706,1.698560,0.000000,-1.497627
3273,1.591254e+00,-0.626829,1.270810,0.144017,3.145987e-15,0.072263,-0.981329,0.218748,-0.856007
3274,-1.329516e+00,1.041355,-1.144058,-0.517373,3.145987e-15,-0.288597,-0.942064,0.703468,0.950797
3275,5.401509e-01,-0.038546,-0.525812,0.244515,3.145987e-15,-1.221919,0.560940,0.780223,-2.124459

In [13]:
# chloramines, sulphate, organic_carbon, Trihalomethanes
df1 = pd.concat([df_input, df['Chloramines']], axis=1)
df2 = pd.concat([df_input, df['Sulfate']], axis=1)
df3 = pd.concat([df_input, df['Organic_carbon']], axis=1)
df4 = pd.concat([df_input, df['Trihalomethanes']], axis=1)

In [14]:
df1.to_csv("data/chloramines.csv", index= False)
df2.to_csv("data/sulphates.csv", index= False)
df3.to_csv("data/organic_carbon.csv", index= False)
df4.to_csv("data/trihalomethanes.csv", index= False)

In [15]:
df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,7.080795,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135
1,3.716080,129.422921,18630.057858,6.635246,333.775777,592.885359,15.180013,56.329076,4.500656
2,8.099124,224.236259,19909.541732,9.275884,333.775777,418.606213,16.868637,66.420093,3.055934
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075